-- Generated by Matcha GUI Builder
local Mouse = game.Players.LocalPlayer:GetMouse()

-- Main window (Square)
local Main window = Drawing.new("Square")
Main window.Visible = true
Main window.Transparency = 1
Main window.ZIndex = 10
Main window.Color = Color3.fromHex("#060b5b")
Main window.Position = Vector2.new(32, 40)
Main window.Size = Vector2.new(507, 334)
Main window.Filled = true

-- Title (Text)
local Title = Drawing.new("Text")
Title.Visible = true
Title.Transparency = 1
Title.ZIndex = 30
Title.Color = Color3.fromHex("#FFFFFF")
Title.Position = Main window.Position + Vector2.new(94, 0)
Title.Text = "Ultimate Mining Tycoon Esp"
Title.Size = 22
Title.Center = false
Title.Outline = true
Title.Font = Drawing.Fonts.Monospace

-- Title Background (Square)
local Title Background = Drawing.new("Square")
Title Background.Visible = true
Title Background.Transparency = 1
Title Background.ZIndex = 20
Title Background.Color = Color3.fromHex("#250ecd")
Title Background.Position = Main window.Position + Vector2.new(0, 0)
Title Background.Size = Vector2.new(507, 23)
Title Background.Filled = true

-- Pickaxe (Text)
local Pickaxe = Drawing.new("Text")
Pickaxe.Visible = true
Pickaxe.Transparency = 1
Pickaxe.ZIndex = 50
Pickaxe.Color = Color3.fromHex("#FFFFFF")
Pickaxe.Position = Main window.Position + Vector2.new(38, 45)
Pickaxe.Text = "Pickaxe"
Pickaxe.Size = 17
Pickaxe.Center = false
Pickaxe.Outline = true
Pickaxe.Font = Drawing.Fonts.Monospace

-- Pickaxe Selection (Dropdown)

-- Dropdown Pickaxe Selection
local Pickaxe Selection = Drawing.new("Square")
Pickaxe Selection.Visible = true
Pickaxe Selection.Transparency = 1
Pickaxe Selection.Color = Color3.fromHex("#250ecd")
Pickaxe Selection.Filled = true
Pickaxe Selection.Size = Vector2.new(134, 24)
Pickaxe Selection.Position = Vector2.new(40, 107)
Pickaxe Selection.ZIndex = 40
local Pickaxe Selection_Text = Drawing.new("Text")
Pickaxe Selection_Text.Visible = true
Pickaxe Selection_Text.Text = "Rusty"
Pickaxe Selection_Text.Size = 19
Pickaxe Selection_Text.Outline = false
Pickaxe Selection_Text.Font = 3
Pickaxe Selection_Text.Color = Color3.fromHex("#ffffff")
Pickaxe Selection_Text.Position = Pickaxe Selection.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Text.ZIndex = 42
local Pickaxe Selection_Arrow = Drawing.new("Text")
Pickaxe Selection_Arrow.Visible = true
Pickaxe Selection_Arrow.Text = "▼"
Pickaxe Selection_Arrow.Size = 15.200000000000001
Pickaxe Selection_Arrow.Outline = false
Pickaxe Selection_Arrow.Color = Color3.fromHex("#ffffff")
Pickaxe Selection_Arrow.Position = Pickaxe Selection.Position + Vector2.new(134 - 20, 2.5)
Pickaxe Selection_Arrow.ZIndex = 42
local Pickaxe Selection_Items = {}
local Pickaxe Selection_Item0_Box = Drawing.new("Square")
Pickaxe Selection_Item0_Box.Visible = false
Pickaxe Selection_Item0_Box.Transparency = 1
Pickaxe Selection_Item0_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item0_Box.Filled = true
Pickaxe Selection_Item0_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item0_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 1)
Pickaxe Selection_Item0_Box.ZIndex = 45
local Pickaxe Selection_Item0_Text = Drawing.new("Text")
Pickaxe Selection_Item0_Text.Visible = false
Pickaxe Selection_Item0_Text.Text = "Rusty"
Pickaxe Selection_Item0_Text.Size = 19
Pickaxe Selection_Item0_Text.Outline = false
Pickaxe Selection_Item0_Text.Font = 3
Pickaxe Selection_Item0_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item0_Text.Position = Pickaxe Selection_Item0_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item0_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item0_Box, Text = Pickaxe Selection_Item0_Text, Value = "Rusty"})
local Pickaxe Selection_Item1_Box = Drawing.new("Square")
Pickaxe Selection_Item1_Box.Visible = false
Pickaxe Selection_Item1_Box.Transparency = 1
Pickaxe Selection_Item1_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item1_Box.Filled = true
Pickaxe Selection_Item1_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item1_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 2)
Pickaxe Selection_Item1_Box.ZIndex = 45
local Pickaxe Selection_Item1_Text = Drawing.new("Text")
Pickaxe Selection_Item1_Text.Visible = false
Pickaxe Selection_Item1_Text.Text = "Copper"
Pickaxe Selection_Item1_Text.Size = 19
Pickaxe Selection_Item1_Text.Outline = false
Pickaxe Selection_Item1_Text.Font = 3
Pickaxe Selection_Item1_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item1_Text.Position = Pickaxe Selection_Item1_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item1_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item1_Box, Text = Pickaxe Selection_Item1_Text, Value = "Copper"})
local Pickaxe Selection_Item2_Box = Drawing.new("Square")
Pickaxe Selection_Item2_Box.Visible = false
Pickaxe Selection_Item2_Box.Transparency = 1
Pickaxe Selection_Item2_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item2_Box.Filled = true
Pickaxe Selection_Item2_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item2_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 3)
Pickaxe Selection_Item2_Box.ZIndex = 45
local Pickaxe Selection_Item2_Text = Drawing.new("Text")
Pickaxe Selection_Item2_Text.Visible = false
Pickaxe Selection_Item2_Text.Text = "Iron"
Pickaxe Selection_Item2_Text.Size = 19
Pickaxe Selection_Item2_Text.Outline = false
Pickaxe Selection_Item2_Text.Font = 3
Pickaxe Selection_Item2_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item2_Text.Position = Pickaxe Selection_Item2_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item2_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item2_Box, Text = Pickaxe Selection_Item2_Text, Value = "Iron"})
local Pickaxe Selection_Item3_Box = Drawing.new("Square")
Pickaxe Selection_Item3_Box.Visible = false
Pickaxe Selection_Item3_Box.Transparency = 1
Pickaxe Selection_Item3_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item3_Box.Filled = true
Pickaxe Selection_Item3_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item3_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 4)
Pickaxe Selection_Item3_Box.ZIndex = 45
local Pickaxe Selection_Item3_Text = Drawing.new("Text")
Pickaxe Selection_Item3_Text.Visible = false
Pickaxe Selection_Item3_Text.Text = "Steel"
Pickaxe Selection_Item3_Text.Size = 19
Pickaxe Selection_Item3_Text.Outline = false
Pickaxe Selection_Item3_Text.Font = 3
Pickaxe Selection_Item3_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item3_Text.Position = Pickaxe Selection_Item3_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item3_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item3_Box, Text = Pickaxe Selection_Item3_Text, Value = "Steel"})
local Pickaxe Selection_Item4_Box = Drawing.new("Square")
Pickaxe Selection_Item4_Box.Visible = false
Pickaxe Selection_Item4_Box.Transparency = 1
Pickaxe Selection_Item4_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item4_Box.Filled = true
Pickaxe Selection_Item4_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item4_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 5)
Pickaxe Selection_Item4_Box.ZIndex = 45
local Pickaxe Selection_Item4_Text = Drawing.new("Text")
Pickaxe Selection_Item4_Text.Visible = false
Pickaxe Selection_Item4_Text.Text = "Platinum"
Pickaxe Selection_Item4_Text.Size = 19
Pickaxe Selection_Item4_Text.Outline = false
Pickaxe Selection_Item4_Text.Font = 3
Pickaxe Selection_Item4_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item4_Text.Position = Pickaxe Selection_Item4_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item4_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item4_Box, Text = Pickaxe Selection_Item4_Text, Value = "Platinum"})
local Pickaxe Selection_Item5_Box = Drawing.new("Square")
Pickaxe Selection_Item5_Box.Visible = false
Pickaxe Selection_Item5_Box.Transparency = 1
Pickaxe Selection_Item5_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item5_Box.Filled = true
Pickaxe Selection_Item5_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item5_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 6)
Pickaxe Selection_Item5_Box.ZIndex = 45
local Pickaxe Selection_Item5_Text = Drawing.new("Text")
Pickaxe Selection_Item5_Text.Visible = false
Pickaxe Selection_Item5_Text.Text = "Titanium"
Pickaxe Selection_Item5_Text.Size = 19
Pickaxe Selection_Item5_Text.Outline = false
Pickaxe Selection_Item5_Text.Font = 3
Pickaxe Selection_Item5_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item5_Text.Position = Pickaxe Selection_Item5_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item5_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item5_Box, Text = Pickaxe Selection_Item5_Text, Value = "Titanium"})
local Pickaxe Selection_Item6_Box = Drawing.new("Square")
Pickaxe Selection_Item6_Box.Visible = false
Pickaxe Selection_Item6_Box.Transparency = 1
Pickaxe Selection_Item6_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item6_Box.Filled = true
Pickaxe Selection_Item6_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item6_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 7)
Pickaxe Selection_Item6_Box.ZIndex = 45
local Pickaxe Selection_Item6_Text = Drawing.new("Text")
Pickaxe Selection_Item6_Text.Visible = false
Pickaxe Selection_Item6_Text.Text = "Infernum"
Pickaxe Selection_Item6_Text.Size = 19
Pickaxe Selection_Item6_Text.Outline = false
Pickaxe Selection_Item6_Text.Font = 3
Pickaxe Selection_Item6_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item6_Text.Position = Pickaxe Selection_Item6_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item6_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item6_Box, Text = Pickaxe Selection_Item6_Text, Value = "Infernum"})
local Pickaxe Selection_Item7_Box = Drawing.new("Square")
Pickaxe Selection_Item7_Box.Visible = false
Pickaxe Selection_Item7_Box.Transparency = 1
Pickaxe Selection_Item7_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item7_Box.Filled = true
Pickaxe Selection_Item7_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item7_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 8)
Pickaxe Selection_Item7_Box.ZIndex = 45
local Pickaxe Selection_Item7_Text = Drawing.new("Text")
Pickaxe Selection_Item7_Text.Visible = false
Pickaxe Selection_Item7_Text.Text = "Diamond"
Pickaxe Selection_Item7_Text.Size = 19
Pickaxe Selection_Item7_Text.Outline = false
Pickaxe Selection_Item7_Text.Font = 3
Pickaxe Selection_Item7_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item7_Text.Position = Pickaxe Selection_Item7_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item7_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item7_Box, Text = Pickaxe Selection_Item7_Text, Value = "Diamond"})
local Pickaxe Selection_Item8_Box = Drawing.new("Square")
Pickaxe Selection_Item8_Box.Visible = false
Pickaxe Selection_Item8_Box.Transparency = 1
Pickaxe Selection_Item8_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item8_Box.Filled = true
Pickaxe Selection_Item8_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item8_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 9)
Pickaxe Selection_Item8_Box.ZIndex = 45
local Pickaxe Selection_Item8_Text = Drawing.new("Text")
Pickaxe Selection_Item8_Text.Visible = false
Pickaxe Selection_Item8_Text.Text = "Mithril"
Pickaxe Selection_Item8_Text.Size = 19
Pickaxe Selection_Item8_Text.Outline = false
Pickaxe Selection_Item8_Text.Font = 3
Pickaxe Selection_Item8_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item8_Text.Position = Pickaxe Selection_Item8_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item8_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item8_Box, Text = Pickaxe Selection_Item8_Text, Value = "Mithril"})
local Pickaxe Selection_Item9_Box = Drawing.new("Square")
Pickaxe Selection_Item9_Box.Visible = false
Pickaxe Selection_Item9_Box.Transparency = 1
Pickaxe Selection_Item9_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item9_Box.Filled = true
Pickaxe Selection_Item9_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item9_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 10)
Pickaxe Selection_Item9_Box.ZIndex = 45
local Pickaxe Selection_Item9_Text = Drawing.new("Text")
Pickaxe Selection_Item9_Text.Visible = false
Pickaxe Selection_Item9_Text.Text = "Adamantium"
Pickaxe Selection_Item9_Text.Size = 19
Pickaxe Selection_Item9_Text.Outline = false
Pickaxe Selection_Item9_Text.Font = 3
Pickaxe Selection_Item9_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item9_Text.Position = Pickaxe Selection_Item9_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item9_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item9_Box, Text = Pickaxe Selection_Item9_Text, Value = "Adamantium"})
local Pickaxe Selection_Item10_Box = Drawing.new("Square")
Pickaxe Selection_Item10_Box.Visible = false
Pickaxe Selection_Item10_Box.Transparency = 1
Pickaxe Selection_Item10_Box.Color = Color3.fromHex("#333333")
Pickaxe Selection_Item10_Box.Filled = true
Pickaxe Selection_Item10_Box.Size = Vector2.new(134, 24)
Pickaxe Selection_Item10_Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * 11)
Pickaxe Selection_Item10_Box.ZIndex = 45
local Pickaxe Selection_Item10_Text = Drawing.new("Text")
Pickaxe Selection_Item10_Text.Visible = false
Pickaxe Selection_Item10_Text.Text = "Unobtainium"
Pickaxe Selection_Item10_Text.Size = 19
Pickaxe Selection_Item10_Text.Outline = false
Pickaxe Selection_Item10_Text.Font = 3
Pickaxe Selection_Item10_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe Selection_Item10_Text.Position = Pickaxe Selection_Item10_Box.Position + Vector2.new(5, 2.5)
Pickaxe Selection_Item10_Text.ZIndex = 46
table.insert(Pickaxe Selection_Items, {Box = Pickaxe Selection_Item10_Box, Text = Pickaxe Selection_Item10_Text, Value = "Unobtainium"})

-- Minimum value (Text)
local Minimum value = Drawing.new("Text")
Minimum value.Visible = true
Minimum value.Transparency = 1
Minimum value.ZIndex = 70
Minimum value.Color = Color3.fromHex("#FFFFFF")
Minimum value.Position = Main window.Position + Vector2.new(179, 115)
Minimum value.Text = "Minimum ore value"
Minimum value.Size = 17
Minimum value.Center = false
Minimum value.Outline = true
Minimum value.Font = Drawing.Fonts.Monospace

-- Minimum Value Selection (Slider)

-- Slider Minimum Value Selection
local Minimum Value Selection = Drawing.new("Square")
Minimum Value Selection.Visible = true
Minimum Value Selection.Transparency = 1
Minimum Value Selection.Color = Color3.fromHex("#444444")
Minimum Value Selection.Filled = true
Minimum Value Selection.Size = Vector2.new(464, 10)
Minimum Value Selection.Position = Vector2.new(53.5, 202)
Minimum Value Selection.ZIndex = 60
local Minimum Value Selection_Value = 100
local Minimum Value Selection_Knob = Drawing.new("Square")
Minimum Value Selection_Knob.Visible = true
Minimum Value Selection_Knob.Transparency = 1
Minimum Value Selection_Knob.Color = Color3.fromHex("#2b00ff")
Minimum Value Selection_Knob.Filled = true
Minimum Value Selection_Knob.Size = Vector2.new(20, 20)
Minimum Value Selection_Knob.Position = Minimum Value Selection.Position + Vector2.new(464 * 0.006666666666666667 - 10, 5 - 10)
Minimum Value Selection_Knob.ZIndex = 61
Minimum Value Selection_Knob.Corner = 100
local Minimum Value Selection_ValueText = Drawing.new("Text")
Minimum Value Selection_ValueText.Visible = true
Minimum Value Selection_ValueText.Text = tostring(math.floor(Minimum Value Selection_Value)) .. "$"
Minimum Value Selection_ValueText.Size = 16
Minimum Value Selection_ValueText.Center = true
Minimum Value Selection_ValueText.Outline = true
Minimum Value Selection_ValueText.Color = Color3.new(1, 1, 1)
Minimum Value Selection_ValueText.Position = Minimum Value Selection.Position + Vector2.new(464/2, -10)
Minimum Value Selection_ValueText.ZIndex = 62

-- Message (Text)
local Message = Drawing.new("Text")
Message.Visible = true
Message.Transparency = 1
Message.ZIndex = 80
Message.Color = Color3.fromHex("#8b8989")
Message.Position = Main window.Position + Vector2.new(251, 179)
Message.Text = "(If the ESP doesn't show anything, it means your pickaxe"
Message.Size = 15
Message.Center = true
Message.Outline = true
Message.Font = Drawing.Fonts.Monospace

-- Message2 (Text)
local Message2 = Drawing.new("Text")
Message2.Visible = true
Message2.Transparency = 1
Message2.ZIndex = 90
Message2.Color = Color3.fromHex("#817f7f")
Message2.Position = Message.Position + Vector2.new(-205, 23)
Message2.Text = "isn't strong enough to mine minerals of that value)"
Message2.Size = 15
Message2.Center = false
Message2.Outline = true
Message2.Font = Drawing.Fonts.Monospace

-- Render Distance (Text)
local Render Distance = Drawing.new("Text")
Render Distance.Visible = true
Render Distance.Transparency = 1
Render Distance.ZIndex = 100
Render Distance.Color = Color3.fromHex("#FFFFFF")
Render Distance.Position = Main window.Position + Vector2.new(151, 226)
Render Distance.Text = "Maximum render distance"
Render Distance.Size = 17
Render Distance.Center = false
Render Distance.Outline = true
Render Distance.Font = Drawing.Fonts.Monospace

-- Render Distance Selection (Slider)

-- Slider Render Distance Selection
local Render Distance Selection = Drawing.new("Square")
Render Distance Selection.Visible = true
Render Distance Selection.Transparency = 1
Render Distance Selection.Color = Color3.fromHex("#444444")
Render Distance Selection.Filled = true
Render Distance Selection.Size = Vector2.new(464, 10)
Render Distance Selection.Position = Vector2.new(53.5, 307)
Render Distance Selection.ZIndex = 110
local Render Distance Selection_Value = 100
local Render Distance Selection_Knob = Drawing.new("Square")
Render Distance Selection_Knob.Visible = true
Render Distance Selection_Knob.Transparency = 1
Render Distance Selection_Knob.Color = Color3.fromHex("#2b00ff")
Render Distance Selection_Knob.Filled = true
Render Distance Selection_Knob.Size = Vector2.new(20, 20)
Render Distance Selection_Knob.Position = Render Distance Selection.Position + Vector2.new(464 * 0.0033333333333333335 - 10, 5 - 10)
Render Distance Selection_Knob.ZIndex = 111
Render Distance Selection_Knob.Corner = 100
local Render Distance Selection_ValueText = Drawing.new("Text")
Render Distance Selection_ValueText.Visible = true
Render Distance Selection_ValueText.Text = tostring(math.floor(Render Distance Selection_Value)) .. ""
Render Distance Selection_ValueText.Size = 16
Render Distance Selection_ValueText.Center = true
Render Distance Selection_ValueText.Outline = true
Render Distance Selection_ValueText.Color = Color3.new(1, 1, 1)
Render Distance Selection_ValueText.Position = Render Distance Selection.Position + Vector2.new(464/2, -10)
Render Distance Selection_ValueText.ZIndex = 112

-- Teleports (Text)
local Teleports = Drawing.new("Text")
Teleports.Visible = true
Teleports.Transparency = 1
Teleports.ZIndex = 150
Teleports.Color = Color3.fromHex("#FFFFFF")
Teleports.Position = Main window.Position + Vector2.new(302, 45)
Teleports.Text = "Teleports"
Teleports.Size = 17
Teleports.Center = false
Teleports.Outline = true
Teleports.Font = Drawing.Fonts.Monospace

-- Plot Teleport (Button)
local Plot Teleport = Drawing.new("Square")
Plot Teleport.Visible = true
Plot Teleport.Transparency = 1
Plot Teleport.ZIndex = 120
Plot Teleport.Color = Color3.fromHex("#250ecd")
Plot Teleport.Position = Teleports.Position + Vector2.new(-122, 23.5)
Plot Teleport.Size = Vector2.new(104, 21)
Plot Teleport.Filled = true

local Plot Teleport_Text = Drawing.new("Text")
Plot Teleport_Text.Text = "Your  Plot"
Plot Teleport_Text.Size = 17
Plot Teleport_Text.Center = true
Plot Teleport_Text.Outline = true
Plot Teleport_Text.Font = 3
Plot Teleport_Text.Color = Color3.fromHex("#ffffff")
Plot Teleport_Text.Position = Plot Teleport.Position + Vector2.new(104/2, 21/2)
Plot Teleport_Text.Visible = true
Plot Teleport_Text.ZIndex = 122

-- Shop Teleport (Button)
local Shop Teleport = Drawing.new("Square")
Shop Teleport.Visible = true
Shop Teleport.Transparency = 1
Shop Teleport.ZIndex = 130
Shop Teleport.Color = Color3.fromHex("#250ecd")
Shop Teleport.Position = Teleports.Position + Vector2.new(94, 23.5)
Shop Teleport.Size = Vector2.new(104, 21)
Shop Teleport.Filled = true

local Shop Teleport_Text = Drawing.new("Text")
Shop Teleport_Text.Text = "Shop"
Shop Teleport_Text.Size = 17
Shop Teleport_Text.Center = true
Shop Teleport_Text.Outline = true
Shop Teleport_Text.Font = 3
Shop Teleport_Text.Color = Color3.fromHex("#ffffff")
Shop Teleport_Text.Position = Shop Teleport.Position + Vector2.new(104/2, 21/2)
Shop Teleport_Text.Visible = true
Shop Teleport_Text.ZIndex = 132

-- Mine Teleport (Button)
local Mine Teleport = Drawing.new("Square")
Mine Teleport.Visible = true
Mine Teleport.Transparency = 1
Mine Teleport.ZIndex = 140
Mine Teleport.Color = Color3.fromHex("#250ecd")
Mine Teleport.Position = Teleports.Position + Vector2.new(-14, 23.5)
Mine Teleport.Size = Vector2.new(104, 21)
Mine Teleport.Filled = true

local Mine Teleport_Text = Drawing.new("Text")
Mine Teleport_Text.Text = "Mine"
Mine Teleport_Text.Size = 17
Mine Teleport_Text.Center = true
Mine Teleport_Text.Outline = true
Mine Teleport_Text.Font = 3
Mine Teleport_Text.Color = Color3.fromHex("#ffffff")
Mine Teleport_Text.Position = Mine Teleport.Position + Vector2.new(104/2, 21/2)
Mine Teleport_Text.Visible = true
Mine Teleport_Text.ZIndex = 142

-- Hide The Ui (Text)
local Hide The Ui = Drawing.new("Text")
Hide The Ui.Visible = true
Hide The Ui.Transparency = 1
Hide The Ui.ZIndex = 170
Hide The Ui.Color = Color3.fromHex("#FFFFFF")
Hide The Ui.Position = Main window.Position + Vector2.new(187, 285)
Hide The Ui.Text = "Keybind to hide"
Hide The Ui.Size = 17
Hide The Ui.Center = false
Hide The Ui.Outline = true
Hide The Ui.Font = Drawing.Fonts.Monospace

-- Keybind To Hide (Keybind)

-- Keybind Keybind To Hide
local Keybind To Hide = Drawing.new("Square")
Keybind To Hide.Visible = true
Keybind To Hide.Transparency = 1
Keybind To Hide.Color = Color3.fromHex("#250ecd")
Keybind To Hide.Filled = true
Keybind To Hide.Size = Vector2.new(134, 14)
Keybind To Hide.Position = Vector2.new(218.5, 349)
Keybind To Hide.ZIndex = 160
local Keybind To Hide_Text = Drawing.new("Text")
Keybind To Hide_Text.Text = "[ V ]"
Keybind To Hide_Text.Size = 9
Keybind To Hide_Text.Center = true
Keybind To Hide_Text.Outline = false
Keybind To Hide_Text.Font = 3
Keybind To Hide_Text.Color = Color3.fromHex("#ffffff")
Keybind To Hide_Text.Position = Keybind To Hide.Position + Vector2.new(134/2, 14/2)
Keybind To Hide_Text.Visible = true
Keybind To Hide_Text.ZIndex = 162
local Keybind To Hide_Key = 0x56
local Keybind To Hide_IsListening = false

local KeyNames = {
    [48] = "0",
    [49] = "1",
    [50] = "2",
    [51] = "3",
    [52] = "4",
    [53] = "5",
    [54] = "6",
    [55] = "7",
    [56] = "8",
    [57] = "9",
    [1] = "LeftMouse",
    [2] = "RightMouse",
    [4] = "MiddleMouse",
    [8] = "Backspace",
    [9] = "Tab",
    [13] = "Enter",
    [16] = "Shift",
    [17] = "Ctrl",
    [18] = "Alt",
    [19] = "Pause",
    [20] = "CapsLock",
    [27] = "Esc",
    [32] = "Space",
    [33] = "PageUp",
    [34] = "PageDown",
    [35] = "End",
    [36] = "Home",
    [37] = "Left",
    [38] = "Up",
    [39] = "Right",
    [40] = "Down",
    [45] = "Insert",
    [46] = "Delete",
    [65] = "A",
    [66] = "B",
    [67] = "C",
    [68] = "D",
    [69] = "E",
    [70] = "F",
    [71] = "G",
    [72] = "H",
    [73] = "I",
    [74] = "J",
    [75] = "K",
    [76] = "L",
    [77] = "M",
    [78] = "N",
    [79] = "O",
    [80] = "P",
    [81] = "Q",
    [82] = "R",
    [83] = "S",
    [84] = "T",
    [85] = "U",
    [86] = "V",
    [87] = "W",
    [88] = "X",
    [89] = "Y",
    [90] = "Z",
    [112] = "F1",
    [113] = "F2",
    [114] = "F3",
    [115] = "F4",
    [116] = "F5",
    [117] = "F6",
    [118] = "F7",
    [119] = "F8",
    [120] = "F9",
    [121] = "F10",
    [122] = "F11",
    [123] = "F12",
}


-- Tab System Functions
local function Tab_Main window_SetVisible(visible)
    if Main window then Main window.Visible = visible end
    if Title then
        Title.Visible = visible
    end
    if Title Background then
        Title Background.Visible = visible
    end
    if Pickaxe then
        Pickaxe.Visible = visible
    end
    if Pickaxe Selection then
        Pickaxe Selection.Visible = visible
        if Pickaxe Selection_Text then Pickaxe Selection_Text.Visible = visible end
        if Pickaxe Selection_Arrow then Pickaxe Selection_Arrow.Visible = visible end
        if not visible then
            for _, item in ipairs(Pickaxe Selection_Items) do
                item.Box.Visible = false
                item.Text.Visible = false
            end
        end
    end
    if Minimum value then
        Minimum value.Visible = visible
    end
    if Minimum Value Selection then
        Minimum Value Selection.Visible = visible
        if Minimum Value Selection_Knob then Minimum Value Selection_Knob.Visible = visible end
        if Minimum Value Selection_ValueText then Minimum Value Selection_ValueText.Visible = visible end
    end
    if Message then
        Message.Visible = visible
    end
    if Message2 then
        Message2.Visible = visible
    end
    if Render Distance then
        Render Distance.Visible = visible
    end
    if Render Distance Selection then
        Render Distance Selection.Visible = visible
        if Render Distance Selection_Knob then Render Distance Selection_Knob.Visible = visible end
        if Render Distance Selection_ValueText then Render Distance Selection_ValueText.Visible = visible end
    end
    if Teleports then
        Teleports.Visible = visible
    end
    if Plot Teleport then
        Plot Teleport.Visible = visible
        if Plot Teleport_Text then Plot Teleport_Text.Visible = visible end
    end
    if Shop Teleport then
        Shop Teleport.Visible = visible
        if Shop Teleport_Text then Shop Teleport_Text.Visible = visible end
    end
    if Mine Teleport then
        Mine Teleport.Visible = visible
        if Mine Teleport_Text then Mine Teleport_Text.Visible = visible end
    end
    if Hide The Ui then
        Hide The Ui.Visible = visible
    end
    if Keybind To Hide then
        Keybind To Hide.Visible = visible
        if Keybind To Hide_Text then Keybind To Hide_Text.Visible = visible end
    end
end

-- ==========================================
-- LÓGICA DE ESP Y TELEPORTS (MATCHA LUA VM)
-- ==========================================

local picks_strength = {
    ["Rusty"] = 7, ["Copper"] = 12, ["Iron"] = 20, ["Steel"] = 35,
    ["Platinum"] = 60, ["Titanium"] = 100, ["Infernum"] = 200,
    ["Diamond"] = 400, ["Mithril"] = 600, ["Adamantium"] = 800,
    ["Unobtainium"] = 1000
}

local ores_data = {
    Tin = {v = 10, r = 6}, Iron = {v = 20, r = 6}, Lead = {v = 30, r = 7},
    Cobalt = {v = 50, r = 12}, Aluminium = {v = 65, r = 18}, Silver = {v = 150, r = 18},
    Uranium = {v = 180, r = 18}, Vanadium = {v = 240, r = 22}, Tungsten = {v = 300, r = 45},
    Gold = {v = 350, r = 22}, Titanium = {v = 400, r = 24}, Molybdenum = {v = 600, r = 75},
    Plutonium = {v = 1000, r = 99}, Palladium = {v = 1200, r = 120}, Mithril = {v = 2000, r = 200},
    Thorium = {v = 3200, r = 270}, Iridium = {v = 3700, r = 180}, Adamantium = {v = 4500, r = 300},
    Rhodium = {v = 15000, r = 300}, Unobtainium = {v = 30000, r = 340},
    Topaz = {v = 75, r = 6}, Emerald = {v = 200, r = 14}, Sapphire = {v = 250, r = 14},
    Ruby = {v = 300, r = 18}, Diamond = {v = 1500, r = 22}, Poudretteite = {v = 1700, r = 75},
    Zultanite = {v = 2300, r = 110}, Grandidierite = {v = 4500, r = 120}, Musgravite = {v = 5800, r = 150},
    Painite = {v = 12000, r = 200}
}

-- Funciones de Teletransporte
local lp = game:GetService("Players").LocalPlayer
local workspace = game:GetService("Workspace")

local function teleportTo(targetPos)
    local char = lp.Character
    if char then
        local hrp = char:FindFirstChild("HumanoidRootPart")
        if hrp then
            hrp.Position = targetPos
        end
    end
end

local function teleportToPlot()
    local plotId = lp:GetAttribute("PlotId")
    if plotId then
        local plots = workspace:FindFirstChild("Plots")
        if plots then
            local myPlot = plots:FindFirstChild(tostring(plotId))
            if myPlot then
                local centre = myPlot:FindFirstChild("Centre")
                if centre then
                    teleportTo(centre.Position)
                end
            end
        end
    end
end

-- Hilos de ESP
local activeOres = {}
local espCache = {}

-- 1. Escáner de minerales (Se actualiza cada segundo para no causar lag)
task.spawn(function()
    while true do
        local folder = workspace:FindFirstChild("PlacedOre")
        local char = lp.Character
        if folder and char and char:FindFirstChild("HumanoidRootPart") then
            local myPos = char:FindFirstChild("HumanoidRootPart").Position
            
            -- Leer los valores actuales directamente de tu UI
            local currentPick = Pickaxe_Selection_Text.Text
            local strength = picks_strength[currentPick] or 0
            local minPrice = Minimum_Value_Selection_Value
            local maxD = Render_Distance_Selection_Value

            local list = {}
            for _, ore in pairs(folder:GetChildren()) do
                if ore:IsA("MeshPart") then
                    -- Distancia calculada con formula general
                    local dist = math.sqrt((ore.Position.X - myPos.X)^2 + (ore.Position.Y - myPos.Y)^2 + (ore.Position.Z - myPos.Z)^2)
                    
                    if dist <= maxD then
                        local mId = ore:GetAttribute("MineId")
                        if mId and ores_data[mId] then
                            local d = ores_data[mId]
                            -- Filtrar por fuerza del pico y precio minimo de tu slider
                            if strength >= d.r and d.v >= minPrice then
                                table.insert(list, {obj = ore, data = d})
                            end
                        end
                    end
                end
            end
            activeOres = list
        end
        task.wait(1)
    end
end)

-- 2. Renderizador (Dibuja los textos a alta velocidad)
task.spawn(function()
    while true do
        local rendered = {}
        local currentPick = Pickaxe_Selection_Text.Text
        local strength = picks_strength[currentPick] or 0

        for _, item in pairs(activeOres) do
            local obj = item.obj
            local d = item.data

            if obj and obj.Parent then
                local pos, onScreen = WorldToScreen(obj.Position)
                if onScreen then
                    if not espCache[obj] then
                        local txt = Drawing.new("Text")
                        txt.Size = 14
                        txt.Center = true
                        txt.Outline = true
                        txt.Font = 3
                        espCache[obj] = txt
                    end
                    local txt = espCache[obj]
                    txt.Visible = true
                    txt.Position = pos
                    txt.Text = obj:GetAttribute("MineId") .. " [$" .. tostring(d.v) .. "]"

                    -- Sistema de colores original
                    if d.r >= strength * 0.8 then
                        txt.Color = Color3.fromHex("#ff1e1e") -- Rojo
                    else
                        txt.Color = Color3.fromHex("#1eff1e") -- Verde
                    end
                    rendered[obj] = true
                end
            end
        end

        -- Limpieza de textos que ya no deben verse
        for obj, txt in pairs(espCache) do
            if not rendered[obj] then
                txt.Visible = false
                if not obj or not obj.Parent then
                    txt:Remove()
                    espCache[obj] = nil
                end
            end
        end

        task.wait(0.01)
    end
end)

-- Input Handling
local dragging = nil
local dragStart = nil
local startPos = nil
local knobStartPos = nil
local lastMouse1 = false

while true do
    wait(0.01)
    if isrbxactive() then
        local mouse1 = ismouse1pressed()
        local mPos = Vector2.new(Mouse.X, Mouse.Y)

        -- Keybind Listeners
        if Keybind To Hide_IsListening then
             for i = 1, 255 do
                 if iskeypressed(i) and not ismouse1pressed() then -- Avoid mouse clicks registering as keys if shared ID
                     Keybind To Hide_Key = i
                     Keybind To Hide_IsListening = false
                     local keyName = KeyNames[i] or "Unknown"
                     Keybind To Hide_Text.Text = "[ " .. keyName .. " ]"
                     Keybind To Hide_Text.Color = Color3.fromHex("#ffffff")
                     pcall(function() onKeyChanged(i) end)
                     wait(0.2) -- Prevent immediate trigger
                     break
                 end
             end
        else
             if iskeypressed(Keybind To Hide_Key) then
                 -- Intelligent Action
                 local newState = not Main window.Visible
                 Main window.Visible = newState
                 Title.Visible = newState
                 Title Background.Visible = newState
                 Pickaxe Selection.Visible = newState
                 Pickaxe Selection_Text.Visible = newState
                 Pickaxe Selection_Arrow.Visible = newState
                 Pickaxe.Visible = newState
                 Minimum Value Selection.Visible = newState
                 Minimum Value Selection_Knob.Visible = newState
                 Minimum Value Selection_ValueText.Visible = newState
                 Minimum value.Visible = newState
                 Message.Visible = newState
                 Message2.Visible = newState
                 Render Distance.Visible = newState
                 Render Distance Selection.Visible = newState
                 Render Distance Selection_Knob.Visible = newState
                 Render Distance Selection_ValueText.Visible = newState
                 Plot Teleport.Visible = newState
                 Plot Teleport_Text.Visible = newState
                 Shop Teleport.Visible = newState
                 Shop Teleport_Text.Visible = newState
                 Mine Teleport.Visible = newState
                 Mine Teleport_Text.Visible = newState
                 Teleports.Visible = newState
                 Keybind To Hide.Visible = newState
                 Keybind To Hide_Text.Visible = newState
                 Hide The Ui.Visible = newState
                 wait(0.2) -- Debounce
             end
        end

        -- Mouse Down (Just Pressed)
        if mouse1 and not lastMouse1 then
            -- Button Pickaxe Selection
            if Pickaxe Selection.Visible and mPos.X >= Pickaxe Selection.Position.X and mPos.X <= Pickaxe Selection.Position.X + Pickaxe Selection.Size.X and
               mPos.Y >= Pickaxe Selection.Position.Y and mPos.Y <= Pickaxe Selection.Position.Y + Pickaxe Selection.Size.Y then
                pcall(function() onChanged() end)
                -- Toggle Dropdown
                local isOpen = Pickaxe Selection_Items[1].Box.Visible
                for _, item in ipairs(Pickaxe Selection_Items) do
                    item.Box.Visible = not isOpen
                    item.Text.Visible = not isOpen
                end
            end
            -- Dropdown Items for Pickaxe Selection
            if Pickaxe Selection_Items[1].Box.Visible then
                for _, item in ipairs(Pickaxe Selection_Items) do
                    if mPos.X >= item.Box.Position.X and mPos.X <= item.Box.Position.X + item.Box.Size.X and
                       mPos.Y >= item.Box.Position.Y and mPos.Y <= item.Box.Position.Y + item.Box.Size.Y then
                        Pickaxe Selection_Text.Text = item.Value
                        -- Close Dropdown
                        for _, it in ipairs(Pickaxe Selection_Items) do
                            it.Box.Visible = false
                            it.Text.Visible = false
                        end
                        if onChanged then pcall(function() onChanged(item.Value) end) end
                    end
                end
            end
-- ==========================================================
-- SECCIÓN DE DETECCIÓN DE CLICS (Dentro del while true do)
-- ==========================================================

-- 1. Botón para ir al Plot (Tu Parcela)
if Plot_Teleport.Visible and mPos.X >= Plot_Teleport.Position.X and mPos.X <= Plot_Teleport.Position.X + Plot_Teleport.Size.X and mPos.Y >= Plot_Teleport.Position.Y and mPos.Y <= Plot_Teleport.Position.Y + Plot_Teleport.Size.Y then
    pcall(function() 
        teleportToPlot() -- Esta función busca tu PlotId automáticamente
    end)
end

-- 2. Botón para ir a la Tienda (Shop)
if Shop_Teleport.Visible and mPos.X >= Shop_Teleport.Position.X and mPos.X <= Shop_Teleport.Position.X + Shop_Teleport.Size.X and mPos.Y >= Shop_Teleport.Position.Y and mPos.Y <= Shop_Teleport.Position.Y + Shop_Teleport.Size.Y then
    pcall(function() 
        teleportTo(Vector3.new(-1550, 10, 20)) 
    end)
end

-- 3. Botón para ir a la Mina (Mine)
if Mine_Teleport.Visible and mPos.X >= Mine_Teleport.Position.X and mPos.X <= Mine_Teleport.Position.X + Mine_Teleport.Size.X and mPos.Y >= Mine_Teleport.Position.Y and mPos.Y <= Mine_Teleport.Position.Y + Mine_Teleport.Size.Y then
    pcall(function() 
        teleportTo(Vector3.new(-1889, 7, -193)) 
    end)
end
            -- Button Keybind To Hide
            if Keybind To Hide.Visible and mPos.X >= Keybind To Hide.Position.X and mPos.X <= Keybind To Hide.Position.X + Keybind To Hide.Size.X and
               mPos.Y >= Keybind To Hide.Position.Y and mPos.Y <= Keybind To Hide.Position.Y + Keybind To Hide.Size.Y then
                pcall(function() onKeyChanged() end)
                -- Keybind Click
                Keybind To Hide_IsListening = true
                Keybind To Hide_Text.Text = "..."
                Keybind To Hide_Text.Color = Color3.fromHex("#FFFF00")
            end
            -- Drag Main window
            if Main window.Visible and mPos.X >= Main window.Position.X and mPos.X <= Main window.Position.X + Main window.Size.X and
               mPos.Y >= Main window.Position.Y and mPos.Y <= Main window.Position.Y + Main window.Size.Y then
                dragging = Main window
                dragStart = mPos
                startPos = Main window.Position
            end
            -- Drag Minimum Value Selection
            if Minimum Value Selection_Knob.Visible and mPos.X >= Minimum Value Selection_Knob.Position.X and mPos.X <= Minimum Value Selection_Knob.Position.X + Minimum Value Selection_Knob.Size.X and
               mPos.Y >= Minimum Value Selection_Knob.Position.Y and mPos.Y <= Minimum Value Selection_Knob.Position.Y + Minimum Value Selection_Knob.Size.Y then
                dragging = Minimum Value Selection_Knob
                dragStart = mPos
                startPos = Minimum Value Selection_Knob.Position
            end
            -- Drag Render Distance Selection
            if Render Distance Selection_Knob.Visible and mPos.X >= Render Distance Selection_Knob.Position.X and mPos.X <= Render Distance Selection_Knob.Position.X + Render Distance Selection_Knob.Size.X and
               mPos.Y >= Render Distance Selection_Knob.Position.Y and mPos.Y <= Render Distance Selection_Knob.Position.Y + Render Distance Selection_Knob.Size.Y then
                dragging = Render Distance Selection_Knob
                dragStart = mPos
                startPos = Render Distance Selection_Knob.Position
            end
        end

        -- Mouse Up (Just Released)
        if not mouse1 and lastMouse1 then
            dragging = nil
        end

        -- Dragging Update
        if dragging and mouse1 then
            local delta = mPos - dragStart
            dragging.Position = startPos + delta
            if dragging == Minimum Value Selection_Knob then
                -- Constrain to track
                local minX = Minimum Value Selection.Position.X
                local maxX = Minimum Value Selection.Position.X + Minimum Value Selection.Size.X
                if dragging.Position.X < minX then dragging.Position = Vector2.new(minX, dragging.Position.Y) end
                if dragging.Position.X > maxX then dragging.Position = Vector2.new(maxX, dragging.Position.Y) end
                dragging.Position = Vector2.new(dragging.Position.X, Minimum Value Selection.Position.Y + 5 - dragging.Size.Y/2)
                -- Calculate Value
                local percent = (dragging.Position.X - minX) / (Minimum Value Selection.Size.X)
                local value = 0 + (15000 - 0) * percent
                Minimum Value Selection_Value = value
                Minimum Value Selection_ValueText.Text = tostring(math.floor(value)) .. "$"
                pcall(function() onChanged(value) end)
            end
            if dragging == Render Distance Selection_Knob then
                -- Constrain to track
                local minX = Render Distance Selection.Position.X
                local maxX = Render Distance Selection.Position.X + Render Distance Selection.Size.X
                if dragging.Position.X < minX then dragging.Position = Vector2.new(minX, dragging.Position.Y) end
                if dragging.Position.X > maxX then dragging.Position = Vector2.new(maxX, dragging.Position.Y) end
                dragging.Position = Vector2.new(dragging.Position.X, Render Distance Selection.Position.Y + 5 - dragging.Size.Y/2)
                -- Calculate Value
                local percent = (dragging.Position.X - minX) / (Render Distance Selection.Size.X)
                local value = 0 + (30000 - 0) * percent
                Render Distance Selection_Value = value
                Render Distance Selection_ValueText.Text = tostring(math.floor(value)) .. ""
                pcall(function() onChanged(value) end)
            end
            if dragging == Main window then
                Title.Position = dragging.Position + Vector2.new(94, 0)
                Title Background.Position = dragging.Position + Vector2.new(0, 0)
                Pickaxe.Position = dragging.Position + Vector2.new(38, 45)
                Pickaxe Selection.Position = dragging.Position + Vector2.new(8, 67)
                Pickaxe Selection_Text.Position = Pickaxe Selection.Position + Vector2.new(5, 2.5)
                Pickaxe Selection_Arrow.Position = Pickaxe Selection.Position + Vector2.new(134 - 20, 2.5)
                for i, item in ipairs(Pickaxe Selection_Items) do
                    item.Box.Position = Pickaxe Selection.Position + Vector2.new(0, 24 * i)
                    item.Text.Position = item.Box.Position + Vector2.new(5, 2.5)
                end
                Minimum value.Position = dragging.Position + Vector2.new(179, 115)
                Minimum Value Selection.Position = dragging.Position + Vector2.new(21.5, 162)
                local percent = (Minimum Value Selection_Value - 0) / (15000 - 0)
                Minimum Value Selection_Knob.Position = Minimum Value Selection.Position + Vector2.new(464 * percent - 10, 5 - 10)
                Minimum Value Selection_ValueText.Position = Minimum Value Selection.Position + Vector2.new(464/2, -10)
                Message.Position = dragging.Position + Vector2.new(251, 179)
                Message2.Position = dragging.Position + Vector2.new(46, 202)
                Render Distance.Position = dragging.Position + Vector2.new(151, 226)
                Render Distance Selection.Position = dragging.Position + Vector2.new(21.5, 267)
                local percent = (Render Distance Selection_Value - 0) / (30000 - 0)
                Render Distance Selection_Knob.Position = Render Distance Selection.Position + Vector2.new(464 * percent - 10, 5 - 10)
                Render Distance Selection_ValueText.Position = Render Distance Selection.Position + Vector2.new(464/2, -10)
                Teleports.Position = dragging.Position + Vector2.new(302, 45)
                Plot Teleport.Position = dragging.Position + Vector2.new(180, 68.5)
                Plot Teleport_Text.Position = Plot Teleport.Position + Vector2.new(104/2, 21/2)
                Shop Teleport.Position = dragging.Position + Vector2.new(396, 68.5)
                Shop Teleport_Text.Position = Shop Teleport.Position + Vector2.new(104/2, 21/2)
                Mine Teleport.Position = dragging.Position + Vector2.new(288, 68.5)
                Mine Teleport_Text.Position = Mine Teleport.Position + Vector2.new(104/2, 21/2)
                Hide The Ui.Position = dragging.Position + Vector2.new(187, 285)
                Keybind To Hide.Position = dragging.Position + Vector2.new(186.5, 309)
                Keybind To Hide_Text.Position = Keybind To Hide.Position + Vector2.new(134/2, 14/2)
            end
        end

        lastMouse1 = mouse1
    end
end
