-- Generated by Matcha GUI Builder
local Mouse = game.Players.LocalPlayer:GetMouse()

-- Main_window (Square)
local Main_window = Drawing.new("Square")
Main_window.Visible = true
Main_window.Transparency = 1
Main_window.ZIndex = 10
Main_window.Color = Color3.fromHex("#060b5b")
Main_window.Position = Vector2.new(32, 40)
Main_window.Size = Vector2.new(507, 334)
Main_window.Filled = true

-- Title (Text)
local Title = Drawing.new("Text")
Title.Visible = true
Title.Transparency = 1
Title.ZIndex = 30
Title.Color = Color3.fromHex("#FFFFFF")
Title.Position = Main_window.Position + Vector2.new(97, 0)
Title.Text = "Ultimate Mining Tycoon Esp"
Title.Size = 22
Title.Center = false
Title.Outline = true
Title.Font = Drawing.Fonts.Monospace

-- Title_Background (Square)
local Title_Background = Drawing.new("Square")
Title_Background.Visible = true
Title_Background.Transparency = 1
Title_Background.ZIndex = 20
Title_Background.Color = Color3.fromHex("#250ecd")
Title_Background.Position = Main_window.Position + Vector2.new(0, 0)
Title_Background.Size = Vector2.new(507, 23)
Title_Background.Filled = true

-- Pickaxe (Text)
local Pickaxe = Drawing.new("Text")
Pickaxe.Visible = true
Pickaxe.Transparency = 1
Pickaxe.ZIndex = 50
Pickaxe.Color = Color3.fromHex("#FFFFFF")
Pickaxe.Position = Main_window.Position + Vector2.new(38, 45)
Pickaxe.Text = "Pickaxe"
Pickaxe.Size = 17
Pickaxe.Center = false
Pickaxe.Outline = true
Pickaxe.Font = Drawing.Fonts.Monospace

-- Pickaxe_Selection (Dropdown)

-- Dropdown Pickaxe_Selection
local Pickaxe_Selection = Drawing.new("Square")
Pickaxe_Selection.Visible = true
Pickaxe_Selection.Transparency = 1
Pickaxe_Selection.Color = Color3.fromHex("#250ecd")
Pickaxe_Selection.Filled = true
Pickaxe_Selection.Size = Vector2.new(134, 24)
Pickaxe_Selection.Position = Vector2.new(40, 107)
Pickaxe_Selection.ZIndex = 40
local Pickaxe_Selection_Text = Drawing.new("Text")
Pickaxe_Selection_Text.Visible = true
Pickaxe_Selection_Text.Text = "Rusty"
Pickaxe_Selection_Text.Size = 19
Pickaxe_Selection_Text.Outline = false
Pickaxe_Selection_Text.Font = 3
Pickaxe_Selection_Text.Color = Color3.fromHex("#ffffff")
Pickaxe_Selection_Text.Position = Pickaxe_Selection.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Text.ZIndex = 42
local Pickaxe_Selection_Arrow = Drawing.new("Text")
Pickaxe_Selection_Arrow.Visible = true
Pickaxe_Selection_Arrow.Text = "▼"
Pickaxe_Selection_Arrow.Size = 15.200000000000001
Pickaxe_Selection_Arrow.Outline = false
Pickaxe_Selection_Arrow.Color = Color3.fromHex("#ffffff")
Pickaxe_Selection_Arrow.Position = Pickaxe_Selection.Position + Vector2.new(134 - 20, 2.5)
Pickaxe_Selection_Arrow.ZIndex = 42
local Pickaxe_Selection_Items = {}
local Pickaxe_Selection_Item0_Box = Drawing.new("Square")
Pickaxe_Selection_Item0_Box.Visible = false
Pickaxe_Selection_Item0_Box.Transparency = 1
Pickaxe_Selection_Item0_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item0_Box.Filled = true
Pickaxe_Selection_Item0_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item0_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 1)
Pickaxe_Selection_Item0_Box.ZIndex = 45
local Pickaxe_Selection_Item0_Text = Drawing.new("Text")
Pickaxe_Selection_Item0_Text.Visible = false
Pickaxe_Selection_Item0_Text.Text = "Rusty"
Pickaxe_Selection_Item0_Text.Size = 19
Pickaxe_Selection_Item0_Text.Outline = false
Pickaxe_Selection_Item0_Text.Font = 3
Pickaxe_Selection_Item0_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item0_Text.Position = Pickaxe_Selection_Item0_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item0_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item0_Box, Text = Pickaxe_Selection_Item0_Text, Value = "Rusty"})
local Pickaxe_Selection_Item1_Box = Drawing.new("Square")
Pickaxe_Selection_Item1_Box.Visible = false
Pickaxe_Selection_Item1_Box.Transparency = 1
Pickaxe_Selection_Item1_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item1_Box.Filled = true
Pickaxe_Selection_Item1_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item1_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 2)
Pickaxe_Selection_Item1_Box.ZIndex = 45
local Pickaxe_Selection_Item1_Text = Drawing.new("Text")
Pickaxe_Selection_Item1_Text.Visible = false
Pickaxe_Selection_Item1_Text.Text = "Copper"
Pickaxe_Selection_Item1_Text.Size = 19
Pickaxe_Selection_Item1_Text.Outline = false
Pickaxe_Selection_Item1_Text.Font = 3
Pickaxe_Selection_Item1_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item1_Text.Position = Pickaxe_Selection_Item1_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item1_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item1_Box, Text = Pickaxe_Selection_Item1_Text, Value = "Copper"})
local Pickaxe_Selection_Item2_Box = Drawing.new("Square")
Pickaxe_Selection_Item2_Box.Visible = false
Pickaxe_Selection_Item2_Box.Transparency = 1
Pickaxe_Selection_Item2_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item2_Box.Filled = true
Pickaxe_Selection_Item2_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item2_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 3)
Pickaxe_Selection_Item2_Box.ZIndex = 45
local Pickaxe_Selection_Item2_Text = Drawing.new("Text")
Pickaxe_Selection_Item2_Text.Visible = false
Pickaxe_Selection_Item2_Text.Text = "Iron"
Pickaxe_Selection_Item2_Text.Size = 19
Pickaxe_Selection_Item2_Text.Outline = false
Pickaxe_Selection_Item2_Text.Font = 3
Pickaxe_Selection_Item2_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item2_Text.Position = Pickaxe_Selection_Item2_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item2_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item2_Box, Text = Pickaxe_Selection_Item2_Text, Value = "Iron"})
local Pickaxe_Selection_Item3_Box = Drawing.new("Square")
Pickaxe_Selection_Item3_Box.Visible = false
Pickaxe_Selection_Item3_Box.Transparency = 1
Pickaxe_Selection_Item3_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item3_Box.Filled = true
Pickaxe_Selection_Item3_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item3_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 4)
Pickaxe_Selection_Item3_Box.ZIndex = 45
local Pickaxe_Selection_Item3_Text = Drawing.new("Text")
Pickaxe_Selection_Item3_Text.Visible = false
Pickaxe_Selection_Item3_Text.Text = "Steel"
Pickaxe_Selection_Item3_Text.Size = 19
Pickaxe_Selection_Item3_Text.Outline = false
Pickaxe_Selection_Item3_Text.Font = 3
Pickaxe_Selection_Item3_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item3_Text.Position = Pickaxe_Selection_Item3_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item3_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item3_Box, Text = Pickaxe_Selection_Item3_Text, Value = "Steel"})
local Pickaxe_Selection_Item4_Box = Drawing.new("Square")
Pickaxe_Selection_Item4_Box.Visible = false
Pickaxe_Selection_Item4_Box.Transparency = 1
Pickaxe_Selection_Item4_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item4_Box.Filled = true
Pickaxe_Selection_Item4_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item4_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 5)
Pickaxe_Selection_Item4_Box.ZIndex = 45
local Pickaxe_Selection_Item4_Text = Drawing.new("Text")
Pickaxe_Selection_Item4_Text.Visible = false
Pickaxe_Selection_Item4_Text.Text = "Platinum"
Pickaxe_Selection_Item4_Text.Size = 19
Pickaxe_Selection_Item4_Text.Outline = false
Pickaxe_Selection_Item4_Text.Font = 3
Pickaxe_Selection_Item4_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item4_Text.Position = Pickaxe_Selection_Item4_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item4_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item4_Box, Text = Pickaxe_Selection_Item4_Text, Value = "Platinum"})
local Pickaxe_Selection_Item5_Box = Drawing.new("Square")
Pickaxe_Selection_Item5_Box.Visible = false
Pickaxe_Selection_Item5_Box.Transparency = 1
Pickaxe_Selection_Item5_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item5_Box.Filled = true
Pickaxe_Selection_Item5_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item5_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 6)
Pickaxe_Selection_Item5_Box.ZIndex = 45
local Pickaxe_Selection_Item5_Text = Drawing.new("Text")
Pickaxe_Selection_Item5_Text.Visible = false
Pickaxe_Selection_Item5_Text.Text = "Titanium"
Pickaxe_Selection_Item5_Text.Size = 19
Pickaxe_Selection_Item5_Text.Outline = false
Pickaxe_Selection_Item5_Text.Font = 3
Pickaxe_Selection_Item5_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item5_Text.Position = Pickaxe_Selection_Item5_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item5_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item5_Box, Text = Pickaxe_Selection_Item5_Text, Value = "Titanium"})
local Pickaxe_Selection_Item6_Box = Drawing.new("Square")
Pickaxe_Selection_Item6_Box.Visible = false
Pickaxe_Selection_Item6_Box.Transparency = 1
Pickaxe_Selection_Item6_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item6_Box.Filled = true
Pickaxe_Selection_Item6_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item6_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 7)
Pickaxe_Selection_Item6_Box.ZIndex = 45
local Pickaxe_Selection_Item6_Text = Drawing.new("Text")
Pickaxe_Selection_Item6_Text.Visible = false
Pickaxe_Selection_Item6_Text.Text = "Infernum"
Pickaxe_Selection_Item6_Text.Size = 19
Pickaxe_Selection_Item6_Text.Outline = false
Pickaxe_Selection_Item6_Text.Font = 3
Pickaxe_Selection_Item6_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item6_Text.Position = Pickaxe_Selection_Item6_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item6_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item6_Box, Text = Pickaxe_Selection_Item6_Text, Value = "Infernum"})
local Pickaxe_Selection_Item7_Box = Drawing.new("Square")
Pickaxe_Selection_Item7_Box.Visible = false
Pickaxe_Selection_Item7_Box.Transparency = 1
Pickaxe_Selection_Item7_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item7_Box.Filled = true
Pickaxe_Selection_Item7_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item7_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 8)
Pickaxe_Selection_Item7_Box.ZIndex = 45
local Pickaxe_Selection_Item7_Text = Drawing.new("Text")
Pickaxe_Selection_Item7_Text.Visible = false
Pickaxe_Selection_Item7_Text.Text = "Diamond"
Pickaxe_Selection_Item7_Text.Size = 19
Pickaxe_Selection_Item7_Text.Outline = false
Pickaxe_Selection_Item7_Text.Font = 3
Pickaxe_Selection_Item7_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item7_Text.Position = Pickaxe_Selection_Item7_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item7_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item7_Box, Text = Pickaxe_Selection_Item7_Text, Value = "Diamond"})
local Pickaxe_Selection_Item8_Box = Drawing.new("Square")
Pickaxe_Selection_Item8_Box.Visible = false
Pickaxe_Selection_Item8_Box.Transparency = 1
Pickaxe_Selection_Item8_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item8_Box.Filled = true
Pickaxe_Selection_Item8_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item8_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 9)
Pickaxe_Selection_Item8_Box.ZIndex = 45
local Pickaxe_Selection_Item8_Text = Drawing.new("Text")
Pickaxe_Selection_Item8_Text.Visible = false
Pickaxe_Selection_Item8_Text.Text = "Mithril"
Pickaxe_Selection_Item8_Text.Size = 19
Pickaxe_Selection_Item8_Text.Outline = false
Pickaxe_Selection_Item8_Text.Font = 3
Pickaxe_Selection_Item8_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item8_Text.Position = Pickaxe_Selection_Item8_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item8_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item8_Box, Text = Pickaxe_Selection_Item8_Text, Value = "Mithril"})
local Pickaxe_Selection_Item9_Box = Drawing.new("Square")
Pickaxe_Selection_Item9_Box.Visible = false
Pickaxe_Selection_Item9_Box.Transparency = 1
Pickaxe_Selection_Item9_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item9_Box.Filled = true
Pickaxe_Selection_Item9_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item9_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 10)
Pickaxe_Selection_Item9_Box.ZIndex = 45
local Pickaxe_Selection_Item9_Text = Drawing.new("Text")
Pickaxe_Selection_Item9_Text.Visible = false
Pickaxe_Selection_Item9_Text.Text = "Adamantium"
Pickaxe_Selection_Item9_Text.Size = 19
Pickaxe_Selection_Item9_Text.Outline = false
Pickaxe_Selection_Item9_Text.Font = 3
Pickaxe_Selection_Item9_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item9_Text.Position = Pickaxe_Selection_Item9_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item9_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item9_Box, Text = Pickaxe_Selection_Item9_Text, Value = "Adamantium"})
local Pickaxe_Selection_Item10_Box = Drawing.new("Square")
Pickaxe_Selection_Item10_Box.Visible = false
Pickaxe_Selection_Item10_Box.Transparency = 1
Pickaxe_Selection_Item10_Box.Color = Color3.fromHex("#333333")
Pickaxe_Selection_Item10_Box.Filled = true
Pickaxe_Selection_Item10_Box.Size = Vector2.new(134, 24)
Pickaxe_Selection_Item10_Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * 11)
Pickaxe_Selection_Item10_Box.ZIndex = 45
local Pickaxe_Selection_Item10_Text = Drawing.new("Text")
Pickaxe_Selection_Item10_Text.Visible = false
Pickaxe_Selection_Item10_Text.Text = "Unobtainium"
Pickaxe_Selection_Item10_Text.Size = 19
Pickaxe_Selection_Item10_Text.Outline = false
Pickaxe_Selection_Item10_Text.Font = 3
Pickaxe_Selection_Item10_Text.Color = Color3.fromHex("#FFFFFF")
Pickaxe_Selection_Item10_Text.Position = Pickaxe_Selection_Item10_Box.Position + Vector2.new(5, 2.5)
Pickaxe_Selection_Item10_Text.ZIndex = 46
table.insert(Pickaxe_Selection_Items, {Box = Pickaxe_Selection_Item10_Box, Text = Pickaxe_Selection_Item10_Text, Value = "Unobtainium"})

-- Minimum_value (Text)
local Minimum_value = Drawing.new("Text")
Minimum_value.Visible = true
Minimum_value.Transparency = 1
Minimum_value.ZIndex = 70
Minimum_value.Color = Color3.fromHex("#FFFFFF")
Minimum_value.Position = Main_window.Position + Vector2.new(179, 115)
Minimum_value.Text = "Minimum ore value"
Minimum_value.Size = 17
Minimum_value.Center = false
Minimum_value.Outline = true
Minimum_value.Font = Drawing.Fonts.Monospace

-- Minimum_Value_Selection (Slider)

-- Slider Minimum_Value_Selection
local Minimum_Value_Selection = Drawing.new("Square")
Minimum_Value_Selection.Visible = true
Minimum_Value_Selection.Transparency = 1
Minimum_Value_Selection.Color = Color3.fromHex("#444444")
Minimum_Value_Selection.Filled = true
Minimum_Value_Selection.Size = Vector2.new(464, 10)
Minimum_Value_Selection.Position = Vector2.new(53.5, 202)
Minimum_Value_Selection.ZIndex = 60
local Minimum_Value_Selection_Value = 100
local Minimum_Value_Selection_Knob = Drawing.new("Square")
Minimum_Value_Selection_Knob.Visible = true
Minimum_Value_Selection_Knob.Transparency = 1
Minimum_Value_Selection_Knob.Color = Color3.fromHex("#2b00ff")
Minimum_Value_Selection_Knob.Filled = true
Minimum_Value_Selection_Knob.Size = Vector2.new(20, 20)
Minimum_Value_Selection_Knob.Position = Minimum_Value_Selection.Position + Vector2.new(464 * 0.006666666666666667 - 10, 5 - 10)
Minimum_Value_Selection_Knob.ZIndex = 61
Minimum_Value_Selection_Knob.Corner = 100
local Minimum_Value_Selection_ValueText = Drawing.new("Text")
Minimum_Value_Selection_ValueText.Visible = true
Minimum_Value_Selection_ValueText.Text = tostring(math.floor(Minimum_Value_Selection_Value)) .. "$"
Minimum_Value_Selection_ValueText.Size = 16
Minimum_Value_Selection_ValueText.Center = true
Minimum_Value_Selection_ValueText.Outline = true
Minimum_Value_Selection_ValueText.Color = Color3.new(1, 1, 1)
Minimum_Value_Selection_ValueText.Position = Minimum_Value_Selection.Position + Vector2.new(464/2, -10)
Minimum_Value_Selection_ValueText.ZIndex = 62

-- Message (Text)
local Message = Drawing.new("Text")
Message.Visible = true
Message.Transparency = 1
Message.ZIndex = 80
Message.Color = Color3.fromHex("#8b8989")
Message.Position = Main_window.Position + Vector2.new(251, 179)
Message.Text = "(If the ESP doesn't show anything, it means your pickaxe"
Message.Size = 15
Message.Center = true
Message.Outline = true
Message.Font = Drawing.Fonts.Monospace

-- Message2 (Text)
local Message2 = Drawing.new("Text")
Message2.Visible = true
Message2.Transparency = 1
Message2.ZIndex = 90
Message2.Color = Color3.fromHex("#817f7f")
Message2.Position = Message.Position + Vector2.new(-205, 23)
Message2.Text = "isn't strong enough to mine minerals of that value)"
Message2.Size = 15
Message2.Center = false
Message2.Outline = true
Message2.Font = Drawing.Fonts.Monospace

-- Render_Distance (Text)
local Render_Distance = Drawing.new("Text")
Render_Distance.Visible = true
Render_Distance.Transparency = 1
Render_Distance.ZIndex = 100
Render_Distance.Color = Color3.fromHex("#FFFFFF")
Render_Distance.Position = Main_window.Position + Vector2.new(151, 226)
Render_Distance.Text = "Maximum render distance"
Render_Distance.Size = 17
Render_Distance.Center = false
Render_Distance.Outline = true
Render_Distance.Font = Drawing.Fonts.Monospace

-- Render_Distance_Selection (Slider)

-- Slider Render_Distance_Selection
local Render_Distance_Selection = Drawing.new("Square")
Render_Distance_Selection.Visible = true
Render_Distance_Selection.Transparency = 1
Render_Distance_Selection.Color = Color3.fromHex("#444444")
Render_Distance_Selection.Filled = true
Render_Distance_Selection.Size = Vector2.new(464, 10)
Render_Distance_Selection.Position = Vector2.new(53.5, 307)
Render_Distance_Selection.ZIndex = 110
local Render_Distance_Selection_Value = 100
local Render_Distance_Selection_Knob = Drawing.new("Square")
Render_Distance_Selection_Knob.Visible = true
Render_Distance_Selection_Knob.Transparency = 1
Render_Distance_Selection_Knob.Color = Color3.fromHex("#2b00ff")
Render_Distance_Selection_Knob.Filled = true
Render_Distance_Selection_Knob.Size = Vector2.new(20, 20)
Render_Distance_Selection_Knob.Position = Render_Distance_Selection.Position + Vector2.new(464 * 0.0033333333333333335 - 10, 5 - 10)
Render_Distance_Selection_Knob.ZIndex = 111
Render_Distance_Selection_Knob.Corner = 100
local Render_Distance_Selection_ValueText = Drawing.new("Text")
Render_Distance_Selection_ValueText.Visible = true
Render_Distance_Selection_ValueText.Text = tostring(math.floor(Render_Distance_Selection_Value)) .. ""
Render_Distance_Selection_ValueText.Size = 16
Render_Distance_Selection_ValueText.Center = true
Render_Distance_Selection_ValueText.Outline = true
Render_Distance_Selection_ValueText.Color = Color3.new(1, 1, 1)
Render_Distance_Selection_ValueText.Position = Render_Distance_Selection.Position + Vector2.new(464/2, -10)
Render_Distance_Selection_ValueText.ZIndex = 112

-- Teleports (Text)
local Teleports = Drawing.new("Text")
Teleports.Visible = true
Teleports.Transparency = 1
Teleports.ZIndex = 150
Teleports.Color = Color3.fromHex("#FFFFFF")
Teleports.Position = Main_window.Position + Vector2.new(302, 45)
Teleports.Text = "Teleports"
Teleports.Size = 17
Teleports.Center = false
Teleports.Outline = true
Teleports.Font = Drawing.Fonts.Monospace

-- Plot_Teleport (Button)
local Plot_Teleport = Drawing.new("Square")
Plot_Teleport.Visible = true
Plot_Teleport.Transparency = 1
Plot_Teleport.ZIndex = 120
Plot_Teleport.Color = Color3.fromHex("#250ecd")
Plot_Teleport.Position = Teleports.Position + Vector2.new(-122, 23.5)
Plot_Teleport.Size = Vector2.new(104, 21)
Plot_Teleport.Filled = true

local Plot_Teleport_Text = Drawing.new("Text")
Plot_Teleport_Text.Text = "Your  Plot"
Plot_Teleport_Text.Size = 17
Plot_Teleport_Text.Center = true
Plot_Teleport_Text.Outline = true
Plot_Teleport_Text.Font = 3
Plot_Teleport_Text.Color = Color3.fromHex("#ffffff")
Plot_Teleport_Text.Position = Plot_Teleport.Position + Vector2.new(104/2, 21/2)
Plot_Teleport_Text.Visible = true
Plot_Teleport_Text.ZIndex = 122

-- Shop_Teleport (Button)
local Shop_Teleport = Drawing.new("Square")
Shop_Teleport.Visible = true
Shop_Teleport.Transparency = 1
Shop_Teleport.ZIndex = 130
Shop_Teleport.Color = Color3.fromHex("#250ecd")
Shop_Teleport.Position = Teleports.Position + Vector2.new(94, 23.5)
Shop_Teleport.Size = Vector2.new(104, 21)
Shop_Teleport.Filled = true

local Shop_Teleport_Text = Drawing.new("Text")
Shop_Teleport_Text.Text = "Shop"
Shop_Teleport_Text.Size = 17
Shop_Teleport_Text.Center = true
Shop_Teleport_Text.Outline = true
Shop_Teleport_Text.Font = 3
Shop_Teleport_Text.Color = Color3.fromHex("#ffffff")
Shop_Teleport_Text.Position = Shop_Teleport.Position + Vector2.new(104/2, 21/2)
Shop_Teleport_Text.Visible = true
Shop_Teleport_Text.ZIndex = 132

-- Mine_Teleport (Button)
local Mine_Teleport = Drawing.new("Square")
Mine_Teleport.Visible = true
Mine_Teleport.Transparency = 1
Mine_Teleport.ZIndex = 140
Mine_Teleport.Color = Color3.fromHex("#250ecd")
Mine_Teleport.Position = Teleports.Position + Vector2.new(-14, 23.5)
Mine_Teleport.Size = Vector2.new(104, 21)
Mine_Teleport.Filled = true

local Mine_Teleport_Text = Drawing.new("Text")
Mine_Teleport_Text.Text = "Mine"
Mine_Teleport_Text.Size = 17
Mine_Teleport_Text.Center = true
Mine_Teleport_Text.Outline = true
Mine_Teleport_Text.Font = 3
Mine_Teleport_Text.Color = Color3.fromHex("#ffffff")
Mine_Teleport_Text.Position = Mine_Teleport.Position + Vector2.new(104/2, 21/2)
Mine_Teleport_Text.Visible = true
Mine_Teleport_Text.ZIndex = 142

-- Hide_The_Ui (Text)
local Hide_The_Ui = Drawing.new("Text")
Hide_The_Ui.Visible = true
Hide_The_Ui.Transparency = 1
Hide_The_Ui.ZIndex = 170
Hide_The_Ui.Color = Color3.fromHex("#FFFFFF")
Hide_The_Ui.Position = Main_window.Position + Vector2.new(187, 285)
Hide_The_Ui.Text = "Keybind to hide"
Hide_The_Ui.Size = 17
Hide_The_Ui.Center = false
Hide_The_Ui.Outline = true
Hide_The_Ui.Font = Drawing.Fonts.Monospace

-- Keybind_To_Hide (Keybind)

-- Keybind Keybind_To_Hide
local Keybind_To_Hide = Drawing.new("Square")
Keybind_To_Hide.Visible = true
Keybind_To_Hide.Transparency = 1
Keybind_To_Hide.Color = Color3.fromHex("#250ecd")
Keybind_To_Hide.Filled = true
Keybind_To_Hide.Size = Vector2.new(134, 14)
Keybind_To_Hide.Position = Vector2.new(218.5, 349)
Keybind_To_Hide.ZIndex = 160
local Keybind_To_Hide_Text = Drawing.new("Text")
Keybind_To_Hide_Text.Text = "[ V ]"
Keybind_To_Hide_Text.Size = 9
Keybind_To_Hide_Text.Center = true
Keybind_To_Hide_Text.Outline = false
Keybind_To_Hide_Text.Font = 3
Keybind_To_Hide_Text.Color = Color3.fromHex("#ffffff")
Keybind_To_Hide_Text.Position = Keybind_To_Hide.Position + Vector2.new(134/2, 14/2)
Keybind_To_Hide_Text.Visible = true
Keybind_To_Hide_Text.ZIndex = 162
local Keybind_To_Hide_Key = 0x56
local Keybind_To_Hide_IsListening = false

local KeyNames = {
    [48] = "0",
    [49] = "1",
    [50] = "2",
    [51] = "3",
    [52] = "4",
    [53] = "5",
    [54] = "6",
    [55] = "7",
    [56] = "8",
    [57] = "9",
    [1] = "LeftMouse",
    [2] = "RightMouse",
    [4] = "MiddleMouse",
    [8] = "Backspace",
    [9] = "Tab",
    [13] = "Enter",
    [16] = "Shift",
    [17] = "Ctrl",
    [18] = "Alt",
    [19] = "Pause",
    [20] = "CapsLock",
    [27] = "Esc",
    [32] = "Space",
    [33] = "PageUp",
    [34] = "PageDown",
    [35] = "End",
    [36] = "Home",
    [37] = "Left",
    [38] = "Up",
    [39] = "Right",
    [40] = "Down",
    [45] = "Insert",
    [46] = "Delete",
    [65] = "A",
    [66] = "B",
    [67] = "C",
    [68] = "D",
    [69] = "E",
    [70] = "F",
    [71] = "G",
    [72] = "H",
    [73] = "I",
    [74] = "J",
    [75] = "K",
    [76] = "L",
    [77] = "M",
    [78] = "N",
    [79] = "O",
    [80] = "P",
    [81] = "Q",
    [82] = "R",
    [83] = "S",
    [84] = "T",
    [85] = "U",
    [86] = "V",
    [87] = "W",
    [88] = "X",
    [89] = "Y",
    [90] = "Z",
    [112] = "F1",
    [113] = "F2",
    [114] = "F3",
    [115] = "F4",
    [116] = "F5",
    [117] = "F6",
    [118] = "F7",
    [119] = "F8",
    [120] = "F9",
    [121] = "F10",
    [122] = "F11",
    [123] = "F12",
}


-- Tab System Functions
local function Tab_Main_window_SetVisible(visible)
    if Main_window then Main_window.Visible = visible end
    if Title then
        Title.Visible = visible
    end
    if Title_Background then
        Title_Background.Visible = visible
    end
    if Pickaxe then
        Pickaxe.Visible = visible
    end
    if Pickaxe_Selection then
        Pickaxe_Selection.Visible = visible
        if Pickaxe_Selection_Text then Pickaxe_Selection_Text.Visible = visible end
        if Pickaxe_Selection_Arrow then Pickaxe_Selection_Arrow.Visible = visible end
        if not visible then
            for _, item in ipairs(Pickaxe_Selection_Items) do
                item.Box.Visible = false
                item.Text.Visible = false
            end
        end
    end
    if Minimum_value then
        Minimum_value.Visible = visible
    end
    if Minimum_Value_Selection then
        Minimum_Value_Selection.Visible = visible
        if Minimum_Value_Selection_Knob then Minimum_Value_Selection_Knob.Visible = visible end
        if Minimum_Value_Selection_ValueText then Minimum_Value_Selection_ValueText.Visible = visible end
    end
    if Message then
        Message.Visible = visible
    end
    if Message2 then
        Message2.Visible = visible
    end
    if Render_Distance then
        Render_Distance.Visible = visible
    end
    if Render_Distance_Selection then
        Render_Distance_Selection.Visible = visible
        if Render_Distance_Selection_Knob then Render_Distance_Selection_Knob.Visible = visible end
        if Render_Distance_Selection_ValueText then Render_Distance_Selection_ValueText.Visible = visible end
    end
    if Teleports then
        Teleports.Visible = visible
    end
    if Plot_Teleport then
        Plot_Teleport.Visible = visible
        if Plot_Teleport_Text then Plot_Teleport_Text.Visible = visible end
    end
    if Shop_Teleport then
        Shop_Teleport.Visible = visible
        if Shop_Teleport_Text then Shop_Teleport_Text.Visible = visible end
    end
    if Mine_Teleport then
        Mine_Teleport.Visible = visible
        if Mine_Teleport_Text then Mine_Teleport_Text.Visible = visible end
    end
    if Hide_The_Ui then
        Hide_The_Ui.Visible = visible
    end
    if Keybind_To_Hide then
        Keybind_To_Hide.Visible = visible
        if Keybind_To_Hide_Text then Keybind_To_Hide_Text.Visible = visible end
    end
end

-- Input Handling
local dragging = nil
local dragStart = nil
local startPos = nil
local knobStartPos = nil
local lastMouse1 = false

while true do
    wait(0.01)
    if isrbxactive() then
        local mouse1 = ismouse1pressed()
        local mPos = Vector2.new(Mouse.X, Mouse.Y)

        -- Keybind Listeners
        if Keybind_To_Hide_IsListening then
             for i = 1, 255 do
                 if iskeypressed(i) and not ismouse1pressed() then -- Avoid mouse clicks registering as keys if shared ID
                     Keybind_To_Hide_Key = i
                     Keybind_To_Hide_IsListening = false
                     local keyName = KeyNames[i] or "Unknown"
                     Keybind_To_Hide_Text.Text = "[ " .. keyName .. " ]"
                     Keybind_To_Hide_Text.Color = Color3.fromHex("#ffffff")
                     pcall(function() onKeyChanged(i) end)
                     wait(0.2) -- Prevent immediate trigger
                     break
                 end
             end
        else
             if iskeypressed(Keybind_To_Hide_Key) then
                 -- Intelligent Action
                 local newState = not Main_window.Visible
                 Main_window.Visible = newState
                 Title.Visible = newState
                 Title_Background.Visible = newState
                 Pickaxe_Selection.Visible = newState
                 Pickaxe_Selection_Text.Visible = newState
                 Pickaxe_Selection_Arrow.Visible = newState
                 Pickaxe.Visible = newState
                 Minimum_Value_Selection.Visible = newState
                 Minimum_Value_Selection_Knob.Visible = newState
                 Minimum_Value_Selection_ValueText.Visible = newState
                 Minimum_value.Visible = newState
                 Message.Visible = newState
                 Message2.Visible = newState
                 Render_Distance.Visible = newState
                 Render_Distance_Selection.Visible = newState
                 Render_Distance_Selection_Knob.Visible = newState
                 Render_Distance_Selection_ValueText.Visible = newState
                 Plot_Teleport.Visible = newState
                 Plot_Teleport_Text.Visible = newState
                 Shop_Teleport.Visible = newState
                 Shop_Teleport_Text.Visible = newState
                 Mine_Teleport.Visible = newState
                 Mine_Teleport_Text.Visible = newState
                 Teleports.Visible = newState
                 Keybind_To_Hide.Visible = newState
                 Keybind_To_Hide_Text.Visible = newState
                 Hide_The_Ui.Visible = newState
                 wait(0.2) -- Debounce
             end
        end

        -- Mouse Down (Just Pressed)
        if mouse1 and not lastMouse1 then
            -- Button Pickaxe_Selection
            if Pickaxe_Selection.Visible and mPos.X >= Pickaxe_Selection.Position.X and mPos.X <= Pickaxe_Selection.Position.X + Pickaxe_Selection.Size.X and
               mPos.Y >= Pickaxe_Selection.Position.Y and mPos.Y <= Pickaxe_Selection.Position.Y + Pickaxe_Selection.Size.Y then
                pcall(function() onChanged() end)
                -- Toggle Dropdown
                local isOpen = Pickaxe_Selection_Items[1].Box.Visible
                for _, item in ipairs(Pickaxe_Selection_Items) do
                    item.Box.Visible = not isOpen
                    item.Text.Visible = not isOpen
                end
            end
            -- Dropdown Items for Pickaxe_Selection
            if Pickaxe_Selection_Items[1].Box.Visible then
                for _, item in ipairs(Pickaxe_Selection_Items) do
                    if mPos.X >= item.Box.Position.X and mPos.X <= item.Box.Position.X + item.Box.Size.X and
                       mPos.Y >= item.Box.Position.Y and mPos.Y <= item.Box.Position.Y + item.Box.Size.Y then
                        Pickaxe_Selection_Text.Text = item.Value
                        -- Close Dropdown
                        for _, it in ipairs(Pickaxe_Selection_Items) do
                            it.Box.Visible = false
                            it.Text.Visible = false
                        end
                        if onChanged then pcall(function() onChanged(item.Value) end) end
                    end
                end
            end
           -- Button Plot_Teleport
  if Plot_Teleport.Visible and mPos.X >= Plot_Teleport.Position.X and mPos.X <= Plot_Teleport.Position.X + Plot_Teleport.Size.X and
  mPos.Y >= Plot_Teleport.Position.Y and mPos.Y <= Plot_Teleport.Position.Y + Plot_Teleport.Size.Y then
      local lp = game:GetService("Players").LocalPlayer
      local plotId = lp:GetAttribute("PlotId")
      if plotId then
          local plotsFolder = workspace:FindFirstChild("Plots")
          if plotsFolder then
              local myPlot = plotsFolder:FindFirstChild(tostring(plotId))
              if myPlot then
                  local centre = myPlot:FindFirstChild("Centre")
                  local char = lp.Character
                  if centre and char and char:FindFirstChild("HumanoidRootPart") then
                      char.HumanoidRootPart.Position = centre.Position
                  end
              end
          end
      end
  end
  
  -- Button Shop_Teleport
  if Shop_Teleport.Visible and mPos.X >= Shop_Teleport.Position.X and mPos.X <= Shop_Teleport.Position.X + Shop_Teleport.Size.X and
  mPos.Y >= Shop_Teleport.Position.Y and mPos.Y <= Shop_Teleport.Position.Y + Shop_Teleport.Size.Y then
      local lp = game:GetService("Players").LocalPlayer
      local char = lp.Character
      if char and char:FindFirstChild("HumanoidRootPart") then
          char.HumanoidRootPart.Position = Vector3.new(-1550, 10, 20)
      end
  end
  
  -- Button Mine_Teleport
  if Mine_Teleport.Visible and mPos.X >= Mine_Teleport.Position.X and mPos.X <= Mine_Teleport.Position.X + Mine_Teleport.Size.X and
  mPos.Y >= Mine_Teleport.Position.Y and mPos.Y <= Mine_Teleport.Position.Y + Mine_Teleport.Size.Y then
      local lp = game:GetService("Players").LocalPlayer
      local char = lp.Character
      if char and char:FindFirstChild("HumanoidRootPart") then
          char.HumanoidRootPart.Position = Vector3.new(-1889, 7, -193)
      end
  end
            -- Button Keybind_To_Hide
            if Keybind_To_Hide.Visible and mPos.X >= Keybind_To_Hide.Position.X and mPos.X <= Keybind_To_Hide.Position.X + Keybind_To_Hide.Size.X and
               mPos.Y >= Keybind_To_Hide.Position.Y and mPos.Y <= Keybind_To_Hide.Position.Y + Keybind_To_Hide.Size.Y then
                pcall(function() onKeyChanged() end)
                -- Keybind Click
                Keybind_To_Hide_IsListening = true
                Keybind_To_Hide_Text.Text = "..."
                Keybind_To_Hide_Text.Color = Color3.fromHex("#FFFF00")
            end
            -- Drag Main_window
            if Main_window.Visible and mPos.X >= Main_window.Position.X and mPos.X <= Main_window.Position.X + Main_window.Size.X and
               mPos.Y >= Main_window.Position.Y and mPos.Y <= Main_window.Position.Y + Main_window.Size.Y then
                dragging = Main_window
                dragStart = mPos
                startPos = Main_window.Position
            end
            -- Drag Minimum_Value_Selection
            if Minimum_Value_Selection_Knob.Visible and mPos.X >= Minimum_Value_Selection_Knob.Position.X and mPos.X <= Minimum_Value_Selection_Knob.Position.X + Minimum_Value_Selection_Knob.Size.X and
               mPos.Y >= Minimum_Value_Selection_Knob.Position.Y and mPos.Y <= Minimum_Value_Selection_Knob.Position.Y + Minimum_Value_Selection_Knob.Size.Y then
                dragging = Minimum_Value_Selection_Knob
                dragStart = mPos
                startPos = Minimum_Value_Selection_Knob.Position
            end
            -- Drag Render_Distance_Selection
            if Render_Distance_Selection_Knob.Visible and mPos.X >= Render_Distance_Selection_Knob.Position.X and mPos.X <= Render_Distance_Selection_Knob.Position.X + Render_Distance_Selection_Knob.Size.X and
               mPos.Y >= Render_Distance_Selection_Knob.Position.Y and mPos.Y <= Render_Distance_Selection_Knob.Position.Y + Render_Distance_Selection_Knob.Size.Y then
                dragging = Render_Distance_Selection_Knob
                dragStart = mPos
                startPos = Render_Distance_Selection_Knob.Position
            end
        end

        -- Mouse Up (Just Released)
        if not mouse1 and lastMouse1 then
            dragging = nil
        end

        -- Dragging Update
        if dragging and mouse1 then
            local delta = mPos - dragStart
            dragging.Position = startPos + delta
            if dragging == Minimum_Value_Selection_Knob then
                -- Constrain to track
                local minX = Minimum_Value_Selection.Position.X
                local maxX = Minimum_Value_Selection.Position.X + Minimum_Value_Selection.Size.X
                if dragging.Position.X < minX then dragging.Position = Vector2.new(minX, dragging.Position.Y) end
                if dragging.Position.X > maxX then dragging.Position = Vector2.new(maxX, dragging.Position.Y) end
                dragging.Position = Vector2.new(dragging.Position.X, Minimum_Value_Selection.Position.Y + 5 - dragging.Size.Y/2)
                -- Calculate Value
                local percent = (dragging.Position.X - minX) / (Minimum_Value_Selection.Size.X)
                local value = 0 + (15000 - 0) * percent
                Minimum_Value_Selection_Value = value
                Minimum_Value_Selection_ValueText.Text = tostring(math.floor(value)) .. "$"
                pcall(function() onChanged(value) end)
            end
            if dragging == Render_Distance_Selection_Knob then
                -- Constrain to track
                local minX = Render_Distance_Selection.Position.X
                local maxX = Render_Distance_Selection.Position.X + Render_Distance_Selection.Size.X
                if dragging.Position.X < minX then dragging.Position = Vector2.new(minX, dragging.Position.Y) end
                if dragging.Position.X > maxX then dragging.Position = Vector2.new(maxX, dragging.Position.Y) end
                dragging.Position = Vector2.new(dragging.Position.X, Render_Distance_Selection.Position.Y + 5 - dragging.Size.Y/2)
                -- Calculate Value
                local percent = (dragging.Position.X - minX) / (Render_Distance_Selection.Size.X)
                local value = 0 + (30000 - 0) * percent
                Render_Distance_Selection_Value = value
                Render_Distance_Selection_ValueText.Text = tostring(math.floor(value)) .. ""
                pcall(function() onChanged(value) end)
            end
            if dragging == Main_window then
                Title.Position = dragging.Position + Vector2.new(97, 0)
                Title_Background.Position = dragging.Position + Vector2.new(0, 0)
                Pickaxe.Position = dragging.Position + Vector2.new(38, 45)
                Pickaxe_Selection.Position = dragging.Position + Vector2.new(8, 67)
                Pickaxe_Selection_Text.Position = Pickaxe_Selection.Position + Vector2.new(5, 2.5)
                Pickaxe_Selection_Arrow.Position = Pickaxe_Selection.Position + Vector2.new(134 - 20, 2.5)
                for i, item in ipairs(Pickaxe_Selection_Items) do
                    item.Box.Position = Pickaxe_Selection.Position + Vector2.new(0, 24 * i)
                    item.Text.Position = item.Box.Position + Vector2.new(5, 2.5)
                end
                Minimum_value.Position = dragging.Position + Vector2.new(179, 115)
                Minimum_Value_Selection.Position = dragging.Position + Vector2.new(21.5, 162)
                local percent = (Minimum_Value_Selection_Value - 0) / (15000 - 0)
                Minimum_Value_Selection_Knob.Position = Minimum_Value_Selection.Position + Vector2.new(464 * percent - 10, 5 - 10)
                Minimum_Value_Selection_ValueText.Position = Minimum_Value_Selection.Position + Vector2.new(464/2, -10)
                Message.Position = dragging.Position + Vector2.new(251, 179)
                Message2.Position = dragging.Position + Vector2.new(46, 202)
                Render_Distance.Position = dragging.Position + Vector2.new(151, 226)
                Render_Distance_Selection.Position = dragging.Position + Vector2.new(21.5, 267)
                local percent = (Render_Distance_Selection_Value - 0) / (30000 - 0)
                Render_Distance_Selection_Knob.Position = Render_Distance_Selection.Position + Vector2.new(464 * percent - 10, 5 - 10)
                Render_Distance_Selection_ValueText.Position = Render_Distance_Selection.Position + Vector2.new(464/2, -10)
                Teleports.Position = dragging.Position + Vector2.new(302, 45)
                Plot_Teleport.Position = dragging.Position + Vector2.new(180, 68.5)
                Plot_Teleport_Text.Position = Plot_Teleport.Position + Vector2.new(104/2, 21/2)
                Shop_Teleport.Position = dragging.Position + Vector2.new(396, 68.5)
                Shop_Teleport_Text.Position = Shop_Teleport.Position + Vector2.new(104/2, 21/2)
                Mine_Teleport.Position = dragging.Position + Vector2.new(288, 68.5)
                Mine_Teleport_Text.Position = Mine_Teleport.Position + Vector2.new(104/2, 21/2)
                Hide_The_Ui.Position = dragging.Position + Vector2.new(187, 285)
                Keybind_To_Hide.Position = dragging.Position + Vector2.new(186.5, 309)
                Keybind_To_Hide_Text.Position = Keybind_To_Hide.Position + Vector2.new(134/2, 14/2)
            end
        end

-- ==========================================
-- LOGICA DEL ESP DE MINERALES
-- ==========================================
local lp = game:GetService("Players").LocalPlayer
local rs = game:GetService("RunService")

local picks = {
    {n = "Rusty", s = 7}, {n = "Copper", s = 12}, {n = "Iron", s = 20},
    {n = "Steel", s = 35}, {n = "Platinum", s = 60}, {n = "Titanium", s = 100},
    {n = "Infernum", s = 200}, {n = "Diamond", s = 400}, {n = "Mithril", s = 600},
    {n = "Adamantium", s = 800}, {n = "Unobtainium", s = 1000}
}

local ores = {
    Tin = {v = 10, r = 6}, Iron = {v = 20, r = 6}, Lead = {v = 30, r = 7},
    Cobalt = {v = 50, r = 12}, Aluminium = {v = 65, r = 18}, Silver = {v = 150, r = 18},
    Uranium = {v = 180, r = 18}, Vanadium = {v = 240, r = 22}, Tungsten = {v = 300, r = 45},
    Gold = {v = 350, r = 22}, Titanium = {v = 400, r = 24}, Molybdenum = {v = 600, r = 75},
    Plutonium = {v = 1000, r = 99}, Palladium = {v = 1200, r = 120}, Mithril = {v = 2000, r = 200},
    Thorium = {v = 3200, r = 270}, Iridium = {v = 3700, r = 180}, Adamantium = {v = 4500, r = 300},
    Rhodium = {v = 15000, r = 300}, Unobtainium = {v = 30000, r = 340},
    Topaz = {v = 75, r = 6}, Emerald = {v = 200, r = 14}, Sapphire = {v = 250, r = 14},
    Ruby = {v = 300, r = 18}, Diamond = {v = 1500, r = 22}, Poudretteite = {v = 1700, r = 75},
    Zultanite = {v = 2300, r = 110}, Grandidierite = {v = 4500, r = 120}, Musgravite = {v = 5800, r = 150},
    Painite = {v = 12000, r = 200}
}

local activeOres = {}
local cache = {}

-- Función auxiliar para obtener la fuerza del pico actual según la UI
local function getCurrentPickaxeStrength()
    local currentName = Pickaxe_Selection_Text.Text
    for _, p in ipairs(picks) do
        if p.n == currentName then return p.s end
    end
    return 7 -- Por defecto Rusty
end

-- Bucle asíncrono para escanear minerales en el Workspace
spawn(function()
    while true do
        local folder = workspace:FindFirstChild("PlacedOre")
        local char = lp.Character
        if folder and char and char:FindFirstChild("HumanoidRootPart") then
            local myPos = char.HumanoidRootPart.Position
            local strength = getCurrentPickaxeStrength()
            local minPrice = Minimum_Value_Selection_Value
            local maxD = Render_Distance_Selection_Value
            local list = {}

            for _, ore in pairs(folder:GetChildren()) do
                if ore:IsA("MeshPart") then
                    local dist = (ore.Position - myPos).Magnitude
                    if dist <= maxD then
                        local mId = ore:GetAttribute("MineId")
                        if mId and ores[mId] then
                            local d = ores[mId]
                            if strength >= d.r and d.v >= minPrice then
                                table.insert(list, {obj = ore, data = d})
                            end
                        end
                    end
                end
            end
            activeOres = list
        end
        task.wait(1)
    end
end)

-- Bucle de renderizado del ESP
rs.RenderStepped:Connect(function()
    -- Validar si la UI está visible para mostrar/ocultar los textos si lo deseas.
    -- (Opcional: puedes agregar `if not Main_window.Visible then...` para apagar el ESP junto con la UI)
    
    local rendered = {}
    local strength = getCurrentPickaxeStrength()

    for _, item in pairs(activeOres) do
        local obj = item.obj
        local d = item.data
        if obj and obj.Parent then
            local pos, onScreen = WorldToScreen(obj.Position)
            if onScreen then
                if not cache[obj] then
                    local txt = Drawing.new("Text")
                    txt.Size = 14
                    txt.Center = true
                    txt.Outline = true
                    cache[obj] = txt
                end
                
                local txt = cache[obj]
                txt.Visible = true
                txt.Position = pos
                txt.Text = obj:GetAttribute("MineId") .. " [$" .. d.v .. "]"
                
                -- Cambia a rojo si apenas puedes minarlo, verde si es fácil
                if d.r >= strength * 0.8 then
                    txt.Color = Color3.fromRGB(255, 30, 30)
                else
                    txt.Color = Color3.fromRGB(30, 255, 30)
                end
                rendered[obj] = true
            end
        end
    end

    -- Limpiar textos en caché que ya no están en pantalla o fueron minados
    for obj, txt in pairs(cache) do
        if not rendered[obj] then
            txt.Visible = false
            if not obj or not obj.Parent then
                txt:Remove()
                cache[obj] = nil
            end
        end
    end
end)
        
        lastMouse1 = mouse1
    end
end
